config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end 
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#followers", as: "followers"
    get "following" => "relationships#following", as: "following"
  end 
  
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  
  root :to =>"homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_user!
    
    def search
        @range = params[:range]
        @word = params[:word]
        
        if @range == "User"
           @users = User.looks(params[:search], params[:word])
        else
           @books = Book.looks(params[:search], params[:word])
        end
        
    end 
    
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<table class="table table-hover table-inverse">
    <% if @range == "User" %>
    <h2>Users search for "<%= @word %>"</h2>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
        </tr>
    </thead>    
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= image_tag user.getprofile_image, size:"50x50" %></td>
            <td><%= user.name %></td>
        </tr>
        <% end %>
    </tbody>
    
    <% else %>
    <h2>Books search for "<%= @word %>"</h2>
    <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td>
                <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image, size:'50x50' %>
                <% end %>
            </td>
            <td><%= link_to book.title , book_path(book.id) %></td>
            <td><%= book.body %></td>
        </tr>
        <% end %>
    </tbody>
    <% end %>
</table>